services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    links:
      - db


  db:
    image: mariadb:10.2
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: deepak
      MYSQL_ROOT_PASSWORD: deepak
      MYSQL_DATABASE: livecompliance
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db:db

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${MAIL_PORT:-1025}:1025'
      - '${MAIL_DASHBOARD_PORT:-8025}:8025'